### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by lele344** [brainfoolong/rcon-web-admin#1]
Hi, thank you for your script but I have an issue and can't use it.
 I'm on dedicated linux server.
 When I try to start the script I received the following messsage:

 fs.writeFile(dir + "/master.zip", contents, {"mode": 0o777}, function
 ^
 SyntaxError: Unexpected token ILLEGAL
 at Module._compile (module.js:439:25)
 at Object.Module._extensions..js (module.js:474:10)
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:312:12)
 at Function.Module.runMain (module.js:497:10)
 at startup (node.js:119:16)
 at node.js:906:3

 and the webservice doesn't start.
 Could you help me to fix this issue?
 Thank you

**Comment by SegaNice** [comment]
Me?  Help?

**Comment by brainfoolong** [comment]
Hi!

Please attach your src/main.js file (the complete file, not pasting the contents here).

**Comment by brainfoolong** [comment]
It seems that some of your files are corrupt.
Did you've cloned from git or downloaded the zip like suggested in the readme?

**Comment by lele344** [comment]
Hi, I follow your guide:

```
sudo apt-get install nodejs npm
sudo npm update npm -g
wget https://codeload.github.com/brainfoolong/rcon-web-admin/zip/master -O rcon-web-admin.zip
unzip rcon-web-admin.zip
mv rcon-web-admin-master rcon-web-admin
cd rcon-web-admin
npm install

[main.txt](https://github.com/brainfoolong/rcon-web-admin/files/719378/main.txt)


node src/main.js install-core-widgets
chmod 0755 -R startscripts *

```
When I used the command `node src/main.js install-core-widgets` I received the error:
```
/home/rustserver/rcon-web-admin/src/main.js:58
        fs.writeFile(dir + "/master.zip", contents, {"mode": 0o777}, function
                                                             ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

```

Attached you can find the src/main.js as required. (renamed into txt file only because github doesn't allow to share js file.
Thank you

**Comment by brainfoolong** [comment]
Thank you. All looks fine right now.
Can you post output of `node -v` and `npm -v`?

**Comment by lele344** [comment]
first command:
 node -v
v0.10.29

second command:
npm -v
1.4.21

Thanks

**Comment by brainfoolong** [comment]
Oh, wow. A very very old version of node. (About 3 years outdated or something).
Which server do you have? Have you the ability to update?

**Comment by lele344** [comment]
Linux Debian-86-jessie-64-minimal 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

yep, this is a dedicated server.

**Comment by lele344** [comment]
ok I make this step:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node 
```

Now when I use the command node -v I see: v7.4.0

**Comment by lele344** [comment]
and if I use
` sh startscripts/start-linux.sh start`
now works fine!!!!!!
Thank you for your support brainfoolong!!!

**Comment by brainfoolong** [comment]
Oh, great :) Glad that i could help. Thanks for posting this issue, i'll try to support older versions as well.
