### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Ryan-Nolan** [brainfoolong/rcon-web-admin#10]
Getting the following error when running this command "node src/main.js install-core-widgets" error also appears when trying to start the script

```
[path-here]/src/main.js:60
        fs.writeFile(dir + "/master.zip", contents, {"mode": 0o777}, function 
                                                             ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

```

**Comment by Ryan-Nolan** [comment]
Hmm hold on i see this has appeared before now....
turns out my server has an old version of nodejs... il update it in a moment...

Might be worth haveing your installer check the version and throw an error thats understandable in your next update? :)

**Comment by brainfoolong** [comment]
Yes, it's because of too old nodejs version. I'll implement some version checks in the next update.
