### ISSUE TITLE
Update from 0.12.1 does not work

### ISSUE THREAD

**Issue by LordRofl** [brainfoolong/rcon-web-admin#12]
Hi,

ich habe heute dein Webadmin installiert und bin auf ein Problem mit dem update-mechanismus gestoßen. Installiert habe ich es mithilfe des Dockerfiles von itzg. Es läuft auch alles, nur das ich nicht verstehe warum er den Volumepfad /opt/rcon-web-admin/db nimmt und nicht /opt/rcon-web-admin, aber das ist ein anderes Thema (vllt?)

Jedenfalls zeigt mir das Webinterface ein verfügbares Update an, aber es passiert einfach nichts. Die Pop-ups erscheinen aber sonst bleibt alles beim alten.

Off-Topic: 
Kannst du mir zeigen wie ein Autobot Skript aussieht, der bei Eingabe !players in den Chat die Spielerzahl zurückgibt?

**Comment by brainfoolong** [comment]
Hi

1. Leider kann ich keinen Support für die Docker Installation geben. Falls dort was nicht funktioniert kann ich nicht sagen warum. Stammt nicht von mir.
2. Leider nein, ich betreibe selbst keine Rust Server mehr.

English wäre hier in den Issues besser, damit auch andere das eventuell nachlesen können.

**Comment by LordRofl** [comment]
Nabend,

Würde es konkret werden, dann schreibe ich das auf englisch nochmal. 

1. Ich glaube ja nicht wirklich das es mit der Dockerinstallation zusammenhängt, das war nur am Rande erwähnt. Wie gesagt, es funktioniert ja sonst wirklich alles.

Ansonsten super Ding, etwas hakelig mit den ganzen klappbaren Elementen, aber durchaus nützlich!

2. Schade, ich habs auch jetzt so halb hinbekommen

**Comment by brainfoolong** [comment]
Ich denke schon das es mit Docker was zu tun haben könnte. Beim Update werden viele Dateien geschrieben und der Service neu gestartet, was sonst im Normalbetrieb nie passiert. Ich selbst kenne Docker nicht und nutze es auch nicht. Habe es gerade nochmal auf einer normalen Installation probiert, da funktioniert es wie es soll.
