### ISSUE TITLE
Support for Ark Survival Evolved

### ISSUE THREAD

**Issue by urdeadagain** [brainfoolong/rcon-web-admin#14]
Hi Great looking gui,

I would love to get some of the functionality running with ark, however the rust board is not working at all, any plans to have a general web gui that will work like your rust web api?

**Comment by brainfoolong** [comment]
Hi!

Sorry, it is not possible to create a general api that work for every game. Every game have it's own special commands and parameters and for that reason a gui has to be made for every game individually.

The only widget the works for almost every game is the console widget.

I don't host ark servers so i cannot give an help on this topic.
