### ISSUE TITLE
Not sure how to fix this.. 

### ISSUE THREAD

**Issue by jonmol60** [brainfoolong/rcon-web-admin#15]
[/share/MD0_DATA/Web/rcon] # npm install
npm ERR! unpack Could not read data for util-deprecate@1.0.2
npm ERR! unpack Could not read data for process-nextick-args@1.0.7
npm ERR! unpack Could not read data for isarray@1.0.0
npm ERR! unpack Could not read data for core-util-is@1.0.2
npm ERR! unpack Could not read data for string_decoder@1.0.3
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN optional dep failed, continuing jsbn@~0.1.0
npm WARN optional dep failed, continuing ecc-jsbn@~0.1.1
npm WARN optional dep failed, continuing bcrypt-pbkdf@^1.0.0
npm WARN optional dep failed, continuing tweetnacl@~0.14.0
npm WARN optional dep failed, continuing bcrypt-pbkdf@^1.0.0
npm WARN optional dep failed, continuing jsbn@~0.1.0
npm WARN optional dep failed, continuing ecc-jsbn@~0.1.1
npm WARN optional dep failed, continuing tweetnacl@~0.14.0
npm ERR! Linux 3.4.6
npm ERR! argv "/share/MD0_DATA/.qpkg/nodejsv4/node/bin/node" "/usr/local/bin/npm                      " "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ENOSPC
npm ERR! errno -28
npm ERR! syscall write

npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! Please include the following file with any support request:
npm ERR!     /share/MD0_DATA/Web/rcon/npm-debug.log
[/share/MD0_DATA/Web/rcon] # npm start

> arma-server-web-admin@0.0.1 start /share/MD0_DATA/Web/rcon
> node app.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'gamedig'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/share/MD0_DATA/Web/rcon/lib/server.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.4.6
npm ERR! argv "/share/MD0_DATA/.qpkg/nodejsv4/node/bin/node" "/usr/local/bin/npm                      " "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! arma-server-web-admin@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arma-server-web-admin@0.0.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the arma-server-web-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs arma-server-web-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls arma-server-web-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /share/MD0_DATA/Web/rcon/npm-debug.log
[/share/MD0_DATA/Web/rcon] #

**Comment by brainfoolong** [comment]
Some ideas

1. Do the install with `sudo`
2. Check `npm -v`
3. Check `node -v`
