### ISSUE TITLE
Apache2 Reverse Proxy error.

### ISSUE THREAD

**Issue by sesipod** [brainfoolong/rcon-web-admin#16]
I'm using rcon-web-admin on a solo Debian server with a secondary Debian server managing my reverse proxy for all of my websites. When I attempt to pass this through my reverse proxy I get an error.  

Connection to backend closed, automatically trying to reconnect in 5 seconds...

--

<VirtualHost *:80>
    ServerName rcon.example.com
    ProxyPreserveHost On
    ProxyPass / http://192.168.1.88:4326/
    ProxyPassReverse / http://192.168.1.88:4326/
</VirtualHost>

**Comment by brainfoolong** [comment]
Please see this issue for reverse proxy this application.
It requires more to do the proxy also for the websocket.

https://github.com/brainfoolong/rcon-web-admin/issues/9
