### ISSUE TITLE
Downloading from  https://codeload.github.com/brainfoolong/rcon-web-admin/zip/master don't give latest version

### ISSUE THREAD

**Issue by TheLeftMoose** [brainfoolong/rcon-web-admin#19]
I hope it is ok to give you a hint, as i am using itzg's docker image. When spawning a container from his docker image the UI tells that a new version is avaiable.

Trying to update while running in the docker container wont do much as that will be long gone when container is down'ed next time.

I am not really that much into github, but i understand that his docker file descripes a place on codeload.github.com (https://github.com/itzg/docker-rcon-web-admin/blob/master/Dockerfile) which downloads a zip with latest master.
Could it be that this CI job hasn't been run for a while and such itzg's image therefore is downloading an old version?

Thanks for your great work!
\d

**Comment by brainfoolong** [comment]
Hi! This is the correct link, it get the current master, which is currently `0.13.2`. This is the newest version, always, automatically.

I have no idea how docker works, so unfortunetely i can't help you here.

**Comment by TheLeftMoose** [comment]
then it could be that dockerhub hasn't detected any changes to itzg's repo, thus no new version.

super thanks. I will give itzg a issue as well, know he has lots of repose so this might have slipped.

chears

**Comment by itzg** [comment]
Yeah, dockerhub was only able to trigger on my image's repo and not this "upstream repo".

@brainfoolong , if you could `git tag` your repo at each release, then I'm already setup to get an email when you do.

**Comment by brainfoolong** [comment]
Ok, i'll do realase management in the future.
