### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by pingfloid** [brainfoolong/rcon-web-admin#20]
src/main.js: line 1: use strict: command not found
src/main.js: line 2: /aquota.group: Permission denied
src/main.js: line 3: config.template.js: command not found
src/main.js: line 4: db/: Is a directory
src/main.js: line 5: Error.stackTraceLimit: command not found
src/main.js: line 7: syntax error near unexpected token `0'
src/main.js: line 7: `process.umask(0);'

wie funktioniert es jetzt?

**Comment by brainfoolong** [comment]
How do you started the script?

**Comment by pingfloid** [comment]
with your installtion guide https://github.com/brainfoolong/rcon-web-admin

**Comment by pingfloid** [comment]
node src/main.js install-core-widgets was the start script

**Comment by brainfoolong** [comment]
Which device? Please also post output of `node -v` and `npm -v`.

**Comment by pingfloid** [comment]
linux ubuntu 16.04 
node -v
-bash: node: command not found
npm -v
3.5.2

**Comment by brainfoolong** [comment]
Ok. You don't have `node` installed. Run the command from the troubleshootin section here 

https://github.com/brainfoolong/rcon-web-admin#troubleshooting

**Comment by pingfloid** [comment]
nice now works great :)

**Comment by pingfloid** [comment]
did you have 1 widget for triggered commands 

for [event] assets/prefabs/npc/cargo plane/cargo_plane.prefab 
or helicopter ?

**Comment by brainfoolong** [comment]
Glad to see that this work now.

Widget for triggered commands: No. I generally don't have rust servers anymore, so also no idea how to do such things.

I close this.
