### ISSUE TITLE
Crash (DeprecationWarning)

### ISSUE THREAD

**Issue by BertiDB** [brainfoolong/rcon-web-admin#21]
rcon-web-admin crash (debian 9)

error.log
(node:28015) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

npm -v
6.5.0-next.0
node -v
v11.6.0

**Comment by brainfoolong** [comment]
Thx, i will look into it.

**Comment by brainfoolong** [comment]
Hi, fixed with latest release. https://github.com/brainfoolong/rcon-web-admin/releases/tag/0.13.3
