### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by jaymann220** [brainfoolong/rcon-web-admin#22]
Love the app!

Few requests/ ideas
have a option to ban for bad language and vac ect...
Rustboard settings > make settings a group option (only admins) so mods can use the player list
Add notes on the player list 
set ban duration (for minor infractions)

Thanks for the wicked app!

**Comment by brainfoolong** [comment]
Thx. Many good ideas. Unfortunetely i don't have resources to do any of this.
