### ISSUE TITLE
backup instructions

### ISSUE THREAD

**Issue by yaliilyaya** [brainfoolong/rcon-web-admin#24]
need instructions to create data backup
What directories or files do you need to save?

**Comment by brainfoolong** [comment]
Hi, for a backup of the apps data just save everything from the "db" folder. Maybe also your `config.js` in your main directory.

**Comment by yaliilyaya** [comment]
Thanks
I think you need to save:
- db
- config.js
- public/widgets

**Comment by brainfoolong** [comment]
Sure, if you have additional widgets than also this folder would be good to save.
