### ISSUE TITLE
Suggestion: link to Docker image or blend into your repo

### ISSUE THREAD

**Issue by itzg** [brainfoolong/rcon-web-admin#3]
So far I have been extremely expressed with your web application. As part of [my minecraft server image](https://hub.docker.com/r/itzg/minecraft-server/) I have had an RCON option, but so far has been awkward/scary to use.

With your web app wrapped up in a Docker container that concern is completely removed!

I was wondering if you could either provide a link to [my published image](https://hub.docker.com/r/itzg/rcon/) as an example

or

I'd be glad to submit a pull request to blend the Dockerfile and docs into your repo.

The source definition files are here
https://github.com/itzg/docker-rcon-web-admin

**Comment by brainfoolong** [comment]
Cool thing 👍 . I'll link it in my readme.
