### ISSUE TITLE
dashboard show nothing

### ISSUE THREAD

**Issue by efsysefsys** [brainfoolong/rcon-web-admin#4]
I install this nice rcon weeb tools on linux / vps , all ok.I add server all ok.But when i press dashboard take my server dashboard show nothing.Error logs clean , nothing in logs.
![bug](https://cloud.githubusercontent.com/assets/17949473/23194009/6395397e-f8b4-11e6-8c6d-28cb92357a09.png)

**Comment by lele344** [comment]
Have you added the widgets?

**Comment by brainfoolong** [comment]
Yes, you have to add widgets to see something.

**Comment by efsysefsys** [comment]
all good , thanks :)

**Comment by brainfoolong** [comment]
NP
