### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Owned67** [brainfoolong/rcon-web-admin#5]
Spam by:
Thu Feb 23 2017 04:25:39 GMT+0100 (Paris, Madrid) 'RconServer [XX.XX.XXX.XXX:XXXXX]: Connection faile
d'

The current selected server is not available anymore. Maybe gone offline?

Very strange, only your app produce this problem for connectng to my server....

In http://playrust.io/map/?XX.XX.XXX.XXX:XXXXX => work fine, i see my server, players etc...

Any idea ?

**Comment by brainfoolong** [comment]
This are different things. Playrust.io requires the public server ip:port. This app is an RCON app, that requires the RCON ip, port and password. I guess you've simply put in the wrong credentials.

**Comment by Owned67** [comment]
No, credentials is corectly set.

**Comment by brainfoolong** [comment]
👍
