### ISSUE TITLE
Currently online players seeing in banlist

### ISSUE THREAD

**Issue by neolectron** [brainfoolong/rcon-web-admin#6]
Hello,

As you can see, i have troubble with this.
Currently online players count is showing in the banlist count emplacement.
And there is no users in the banlist either.
So i can't perform any action on any users.
Deleting and adding the widget again fixed it.

plateform      : linux
os                  : debian8
node version : 7.x.x

**Comment by brainfoolong** [comment]
Hi, are your running with web.rcon or without?
