### ISSUE TITLE
Server Wont Start

### ISSUE THREAD

**Issue by erich199** [brainfoolong/rcon-web-admin#7]
Hello,
I've set this up on my linux server as per the directions. When I go to start the sh file, it says the following:
Starting the RCON web admin server
RCON web admin server could not start

When I go to check the log files, they are empty. Wondering if I missed a step somewhere.

**Comment by brainfoolong** [comment]
Try `node src/main.js start` in the root directory of the application. It may show you more debug information.

**Comment by erich199** [comment]
I actually followed these directions: 
http://stackoverflow.com/questions/20031849/how-can-i-find-my-node-js-files-in-linux-usr-bin-node-is-not-working/32740546#32740546

and got it working

**Comment by brainfoolong** [comment]
Great, thx for information, node was not properly installed/available as it seems.
