### ISSUE TITLE
Error Logs

### ISSUE THREAD

**Issue by erich199** [brainfoolong/rcon-web-admin#8]
Hello, 
I noticed today that this was in my error logs: 
DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:2269)

Is this something that is an issue with the script or node?

**Comment by brainfoolong** [comment]
Good question, the error refers to node but it's unclear with this message alone. Which `node -v` do you have?

**Comment by erich199** [comment]
I checked it today and it says I'm running node version 7.8.0

**Comment by brainfoolong** [comment]
Than you are on a very recent version, that's good. I don't know where this error come from. I will look over the code, maybe i find something.

**Comment by brainfoolong** [comment]
Hi, i looked over the code and found one possible issue. Can you verify that this message will be added to the error log when you try to download any logfile in the settings?

**Comment by erich199** [comment]
So I tried to download from the interface, it showed all the error messages. When I went to look at the logs in the FTP, the filesize was huge and it was blank.

**Comment by brainfoolong** [comment]
Really weird. Well, you can just ignore those kind of messages but i'll try to push out an update soon that maybe fix this problem.

**Comment by brainfoolong** [comment]
Maybe fixed with todays update.
