### ISSUE TITLE
SSL - SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by will2therich** [brainfoolong/rcon-web-admin#9]
Hi,

I am an director for a hosting company and we wish to provide service to an RCon panel, and we really like yours however we would NEED to put an SSL certificate over it, when doing this via  reverse proxy on apache. however while this works sortof the page actually https://rcon.flareservers.co.uk/. the error looks to be 
SecurityError: The operation is insecure. within socket.js line 58, is there anything you can do to sort this? would have a look myself but I'm a PHP guy, If we could get this working and smoothly we will defo be donating to you to show our love.

Thanks,
Will,
Flareservers Director - Head Of New Developments

**Comment by brainfoolong** [comment]
The problem seems to be the proxy for the websocket. 
You also need to proxy websockets properly with a valid certificate.
I've not done something like that before, so i cannot really help here.
I don't know if websocket can be proxied properly.

It runs on that port
https://rcon.flareservers.co.uk/wsport

Your websocket refer to https://websock.flareservers.co.uk which leads to your homepage and an invalid certificate. Seems like the websocket proxy thingy isn't configured right.

**Comment by will2therich** [comment]
Hi @brainfoolong 
So I have managed to get the websocket reversed proxied(by the looks of things anyways)
I now get this error 
WebSocket connection to 'wss://socket.flareservers.co.uk/' failed: Error during WebSocket handshake: Unexpected response code: 426
`Socket.connect = function (callback) {
    var cb = function () {
        var con = new WebSocket('wss://' + 'socket.flareservers.co.uk');`
I have only eddited this any ideas? i have never messed with websockets before
Thanks,
Will

**Comment by brainfoolong** [comment]
I guess this can help you
https://github.com/socketio/socket.io/issues/1942

**Comment by will2therich** [comment]
Hi @brainfoolong 
So having looked into the error 426 this is indicating upgrade needed,
so does the page if you goto https://socket.flareservers.co.uk so seems like thats the issue here (at least I hope)

**Comment by brainfoolong** [comment]
Right now, there is no correct mapping to a websocket on https://socket.flareservers.co.uk . Now it show the error "connection closed", means there is no websocket listening here.

**Comment by brainfoolong** [comment]
I will try to do a setup with SSL tomorrow, maybe i can give you some helpful information than.

**Comment by will2therich** [comment]
HI @brainfoolong 
This is what I've got so far,
![image](https://cloud.githubusercontent.com/assets/24435180/26325462/e2f19558-3f2e-11e7-9642-06e80fc65ded.png)


this is my current virtual host setup
`
<IfModule mod_ssl.c>
<VirtualHost *:443>
  ProxyPreserveHost On
  ProxyRequests Off
	ServerName websock.flareservers.co.uk
	ServerAdmin webmaster@localhost
	ServerAlias websock.flareservers.co.uk
	DocumentRoot "/var/www/"
	ProxyPass /ws2/ ws://websock.flareservers.co.uk:4327
  	ProxyPass /wss2/ wss://websock.flareservers.co.uk:4327
SSLCertificateFile /etc/letsencrypt/live/websock.flareservers.co.uk/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/websock.flareservers.co.uk/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
`

**Comment by brainfoolong** [comment]
Can you get it back to the point where you had the `426` error response, this was the closest to get it working. Than try adding something like that to your config, make sure you have the `header module` enabled in apache.

    Header set Connection "upgrade"
    Header set Upgrade "websocket"

**Comment by brainfoolong** [comment]
Here is an additional help thread especially for apache websocket config
https://forum.mattermost.org/t/solved-apache2-reverseproxy-with-websocket-https/437/3

**Comment by will2therich** [comment]
Hi,
Still no luck im afraid,
I have also tried this https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html Seems to be Apaches new built in way but still no luck :(

**Comment by brainfoolong** [comment]
Ok i got it working with Apache 2.4.
1. Update to latest version of this repository (Update pushed out)
2. Enable apache mod "proxy_wstunnel"
3. This is my apache config for the proxy, modify it to your needs and your domain

```
<VirtualHost *:443> 
	ProxyPreserveHost On 
	ProxyRequests Off 
	ServerName test.0x.at
	DocumentRoot c:\www
	ProxyPass /ws ws://test.0x.at:4327
	ProxyPassReverse /ws ws://test.0x.at:4327
	ProxyPass / http://test.0x.at:4326/
	SSLEngine on
	SSLCertificateFile "C:\srv\apache\certs/test.0x.at.crt"
	SSLCertificateKeyFile "C:\srv\apache\certs/test.0x.at.key"
</VirtualHost> 
```

3. Copy `config.template.js` to `config.js` in your application root directory (config has been updated)
4. Modify `websocketUrlSsl` and insert this (you need to insert your own domain): `wss://test.0x.at/ws` - Let `websocketUrl` untouched
5. Open the application, should work now.

**Comment by will2therich** [comment]
Thank you for this! I will give it a shot!

**Comment by will2therich** [comment]
Absolutely perfect! Thank you very much!

**Comment by brainfoolong** [comment]
I'm glad that it work for you.
